futureConcerts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('playlistLinks.urls')),
]

playlistLinks/urls.py
from django.urls import path

from . import views

app_name = 'playlistLinks'
urlpatterns = [
    path('', views.home, name='home'),
    path('process/',views.getData,name='getData'),
    path('<int:user_id>/concerts/',views.concerts,name='concerts'),
    path('delete/',views.inputForDelete,name='inputForDelete'),
    path('deleting',views.delete,name='deleting'),
    path('<str:user_email>/deleted/',views.deleteDone,name='deleteDone'),
    path('getConcerts/',views.getConcerts,name='getConcerts'),
    path('concerts/',views.inputForConcerts,name='inputForConcerts'),
    path('update/<str:city>/',views.updateAllConcerts,name='updateAllConcerts')
]

playlistLinks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

# Create your models here.
class User(models.Model):
	email = models.CharField(max_length=100)
	create_date = models.DateTimeField('date created')
	city = models.CharField(max_length=100,default='Chicago')

	def __str__(self):
		return self.email

class Artist(models.Model):
	name = models.CharField(max_length=100)
	users = models.ManyToManyField(User)

	def __str__(self):
		return self.name

class Concert(models.Model):
	band = models.CharField(max_length=300)
	venue = models.CharField(max_length=300)
	concert_date = models.DateTimeField('date of concert')
	city = models.CharField(max_length=300,default='Chicago')

	def __str__(self):
		return self.band + '@ ' + self.venue 

class Links(models.Model):
	url = models.CharField(max_length=100)
	users = models.ManyToManyField(User)

	def __str__(self):
		return self.url

class Update(models.Model):
	last = models.DateTimeField('last updated')
	city = models.CharField(max_length=30,default='chicago')
	def __str__(self):
		return self.last.strftime('%m-%d-%Y')

playlistLinks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404,render
from django.template import loader
from django.urls import reverse
from .models import User,Links
from datetime import datetime
from . import calculations as c

def home(request):
	# cities = {'cities': ['Chicago','Boston']}
	return render(request,'playlistLinks/home.html')

def getData(request):
	try:
		email = request.POST.get('email','nothing')
		city = request.POST.get('city',False)
		links = request.POST.get('links','')

		links = [x.strip() for x in links.split(',')]

		if email == 'nothing' or '@' not in email:
			return render(request,'playlistLinks/links.html',{'error_message':"Did not enter valid email"})
		if not city or city == '':
			return render(request,'playlistLinks/links.html',{'error_message':"Did not select a city"})
		if links[0] == '':
			return render(request,'playlistLinks/links.html',{'error_message':"Did not give a proper link"})
	except KeyError as e:
		print(e)
		return render(request,'playlistLinks/links.html',{'error_message':"Something went wrong, try again"})

	#adding to database if doesn't already exist
	try:
		u = User.objects.get(email=email)
	except User.DoesNotExist:
		u = User(email=email,create_date = datetime.today(),city=city)
		u.save()
	user_artists = c.getArtists(links)
	#user_concerts = c.getUsersConcerts(city,user_artists,180)
	c.addArtistsToDB(u,user_artists)
	c.addLinksToDB(u,links)
	#c.sftp('db.sqlite3','/emailer/')
	return HttpResponseRedirect(reverse('playlistLinks:concerts',args=(u.id,)))

def concerts(request,user_id):
	u = get_object_or_404(User,pk=user_id)
	user_artists = u.artist_set.all()
	print(len(user_artists))
	user_concerts = c.getUsersConcerts(u.city,user_artists)
	return render(request,'playlistLinks/concerts.html',{'concerts':user_concerts})

def inputForDelete(request):
	return render(request,'playlistLinks/delete.html')

def delete(request):
	user = get_object_or_404(User,email=request.POST.get('email','nothing'))
	user_id = user.id
	try:
		User.objects.filter(id=user_id).delete()
	except User.DoesNotExist:
		return render(request,'playlistLinks/home.html')
	return HttpResponseRedirect(reverse('playlistLinks:deleteDone',args=(user_email,)))

def deleteDone(request,email):
	return render(request,'playlistLinks/deleted.html',{'email':email})

def getConcerts(request):
	try:
		email = request.POST.get('email','nothing')
		if email == 'nothing' or '@' not in email:
			return render(request,'playlistLinks/getConcerts.html',{'error_message':"Did not enter valid email"})
	except KeyError as e:
		return render(request,'playlistLinks/links.html',{'error_message':"Something went wrong, try again"})
	user = get_object_or_404(User,email=email)
	user_id = user.id
	return HttpResponseRedirect(reverse('playlistLinks:concerts',args=(user.id,)))

def inputForConcerts(request):
	return render(request,'playlistLinks/getConcerts.html')

def updateAllConcerts(request,city):
	c.addConcertsToDB(city)
	return render(request,'playlistLinks/updated.html')

futureConcerts/templates/playlistLinks/artists.html
<html>
<center>
<h1>View the artists in the database</h1>
<br>
<input type="text" name="email" placeholder="enter your email">
<br>
</center>
</html>

futureConcerts/templates/playlistLinks/concerts.html
<html>
<center>
<h1>your upcoming concerts:</h1>
<br>
<ul>
{% for concert in concerts %}
	<li>{{concert}}</li>
	<br>
{% endfor %}
</ul>
<br>
<br>
<a href="{% url 'playlistLinks:home' %}">home</a>
</center>
</html>

futureConcerts/templates/playlistLinks/delete.html
<html>
<center>
<h1>Remove your email from the database</h1>
<form action="{% url 'playlistLinks:deleting' %}" method="post">
	{% csrf_token %}
	<input type="text" name="email" placeholder="enter your email">
	<br>
	<br>
<input type="submit" value="submit">
</form>
</center>
</html>

futureConcerts/templates/playlistLinks/deleteDone.html
<html>
<center>
<h1>Goodbye {{email}}</h1>
</center>
</html>

futureConcerts/templates/playlistLinks/getConcerts.html
<html>
<center>
<h1>Enter email to display concerts</h1>
<form action="{% url 'playlistLinks:getConcerts' %}" method="post">
	{% csrf_token %}
	<input type="text" name="email" placeholder="enter your email">
	<br>
	<br>
<input type="submit" value="submit">
</form>
</center>
</html>

futureConcerts/templates/playlistLinks/home.html
<html>
<center>
<h1>Get your Spotify artist upcoming concerts emailed to you every week</h1>
<br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'playlistLinks:getData' %}" method="post" id="user_deets">
	{% csrf_token %}
	<input type="text" name="email" placeholder="enter your email">
	<br>
	<br>
	<label>City to look for concerts:</label>
	<br>
	<br>
	<select name="city">
		<option value="">your city</option>
		<option value="chicago">Chicago</option>
		<option value="boston">Boston</option>
		<option value="losangeles">Los Angeles</option>
		<option value="newyork">New York</option>
		<option value="austin">Austin</option>
		<option value="washington">Washington DC</option>
	</select>
	<br>
	<br>
	<input type="text" name="links" placeholder="enter links to playlists seperated by a comma (,)" size=60>
	<br>
	<br>
<input type="submit" value="submit">
<br>
<br>
<a href="{% url 'playlistLinks:inputForDelete' %}">Delete your email from database</a>
<br>
<br>
<a href="{% url 'playlistLinks:inputForConcerts' %}">View your upcoming concerts</a>
</form>
</center>
</html>

futureConcerts/templates/playlistLinks/updated.html
<html>
<center>
<h2>Done with that city</h2>
</center>
</html>

playlistLinks/templates/playlistLinks/artists.html
<html>
<center>
<h1>View the artists in the database</h1>
<br>
<input type="text" name="email" placeholder="enter your email">
<br>
</center>
</html>

playlistLinks/templates/playlistLinks/concerts.html
<html>
<center>
<h1>your upcoming concerts:</h1>
<br>
<ul>
{% for concert in concerts %}
	<li>{{concert}}</li>
	<br>
{% endfor %}
</ul>
<br>
<br>
<a href="{% url 'playlistLinks:home' %}">home</a>
</center>
</html>

playlistLinks/templates/playlistLinks/delete.html
<html>
<center>
<h1>Remove your email from the database</h1>
<form action="{% url 'playlistLinks:deleting' %}" method="post">
	{% csrf_token %}
	<input type="text" name="email" placeholder="enter your email">
	<br>
	<br>
<input type="submit" value="submit">
</form>
</center>
</html>

playlistLinks/templates/playlistLinks/deleteDone.html
<html>
<center>
<h1>Goodbye {{email}}</h1>
</center>
</html>

playlistLinks/templates/playlistLinks/getConcerts.html
<html>
<center>
<h1>Enter email to display concerts</h1>
<form action="{% url 'playlistLinks:getConcerts' %}" method="post">
	{% csrf_token %}
	<input type="text" name="email" placeholder="enter your email">
	<br>
	<br>
<input type="submit" value="submit">
</form>
</center>
</html>

playlistLinks/templates/playlistLinks/home.html
<html>
<center>
<h1>Get your Spotify artist upcoming concerts emailed to you every week</h1>
<br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'playlistLinks:getData' %}" method="post" id="user_deets">
	{% csrf_token %}
	<input type="text" name="email" placeholder="enter your email">
	<br>
	<br>
	<label>City to look for concerts:</label>
	<br>
	<br>
	<select name="city">
		<option value="">your city</option>
		<option value="chicago">Chicago</option>
		<option value="boston">Boston</option>
		<option value="losangeles">Los Angeles</option>
		<option value="newyork">New York</option>
		<option value="austin">Austin</option>
		<option value="washington">Washington DC</option>
	</select>
	<br>
	<br>
	<input type="text" name="links" placeholder="enter links to playlists seperated by a comma (,)" size=60>
	<br>
	<br>
<input type="submit" value="submit">
<br>
<br>
<a href="{% url 'playlistLinks:inputForDelete' %}">Delete your email from database</a>
<br>
<br>
<a href="{% url 'playlistLinks:inputForConcerts' %}">View your upcoming concerts</a>
</form>
</center>
</html>

playlistLinks/templates/playlistLinks/updated.html
<html>
<center>
<h2>Done with that city</h2>
</center>
</html>